### ISSUE TITLE
getTables() does not list .inner. tables

### ISSUE THREAD

**Issue by SaltTan** [yandex/clickhouse-jdbc#129]
I suppose it happened when different types were assigned to different objects.
I can see .inner. tables if I use 0.1.14, and all objects are listed as 'table'.
With 0.1.25 or 0.1.26 there are tables, views and others, and no .inner. tables.

**Comment by serebrserg** [comment]
Hello. Thanks.
I think this was on purpose in one of pull requests, because .inner. tables were considered as an implementation detail. I've checked with ClickHouse developers and came to conclusion that:
1) this implementation detail had leaked, which means it is quite public now
2) it is better if driver conforms with clickhouse-client

Released in 0.1.28
