### ISSUE TITLE
Float64 gets sorted as string

### ISSUE THREAD

**Issue by SaltTan** [yandex/clickhouse-jdbc#144]
It started in 0.1.26 actually.
I use SQL Workbench/J (http://www.sql-workbench.net/).
Float64 gets sorted as string
![screen shot 2017-10-10 at 5 58 14 pm](https://user-images.githubusercontent.com/20357526/31410311-a9f0d492-ade4-11e7-9609-01c6fe072218.png)
Float32 gets sorted as numbers
![screen shot 2017-10-10 at 5 59 05 pm](https://user-images.githubusercontent.com/20357526/31410338-bb4c1e2c-ade4-11e7-8e39-1b0b794fbc05.png)
This is the difference that I can see in the application:
![screen shot 2017-10-10 at 5 59 36 pm](https://user-images.githubusercontent.com/20357526/31410375-ce952528-ade4-11e7-8282-2cf4d6acb5da.png)
Unfortunately I cannot easily see how the types were interpreted in 0.1.25 because of the 'Unknown identifier: default_type' error, but I checked with a JDBC driver for another database, sorting works correctly for data types that mapped to 'Double'

**Comment by serebrserg** [comment]
The driver returned java.sql.Types.Float for Float32 and Float64 before 0.1.26 and started  to return java.sql.Types.DOUBLE for Float64 after it.
DOUBLE looks correct for Float64.
The reason why it is sorted as string needs investigation in sql workbench. In Intellij plugin it is sorted correctly.
Please reopen or submit a pull request if you find specific problem in sql workbench and it is due to the values returned from the driver.

**Comment by SaltTan** [comment]
"The sorting is determined by the value the driver returns.
SQL Workbench uses ResultSet.getObject() for base data types like Double or Decimal.
Most probably the driver does not properly return a Double object when calling ResultSet.getObject()"
Does this ring any bells?

**Comment by serebrserg** [comment]
Yes, now I see the problem. getObject for DOUBLE returns String. Thanks.

**Comment by serebrserg** [comment]
Released in 0.1.32
