### ISSUE TITLE
Is connection url support nginx http proxy?

### ISSUE THREAD

**Issue by wuyinggui** [yandex/clickhouse-jdbc#163]
my default http client port 8123 is not open, only 80 port is open,I use nginx proxy_pass to mapping this port, like this:
 location /clickhouse {
                proxy_pass http://127.0.0.1:8123;
 }

I want to use url with 'jdbc:clickhouse://xxxx/clickhouse/default'

the program says:
"port is missed or wrong"
but when i use 'jdbc:clickhouse://xxxx:80/clickhouse/default'

the program says ：
"wrong database name path: '/clickhouse/default'"

need your help!
Many thanks!

**Comment by serebrserg** [comment]
Hello.
It is expected that url is
`jdbc:clickhouse://<host>:<port>[/<database>]`
`/clickhouse/default` is not correct database name, so the behavior you describe is correct.
You can either proxy_pass `location /` instead of `location /clickhouse` or
proxy_pass based on domain name like this https://serverfault.com/questions/579285/how-to-proxy-a-server-based-on-domain-name-of-request-using-nginx but also `location /` or open any other port specially for ClickHouse http interface.

**Comment by wuyinggui** [comment]
Hi serebrserg,Thanks for your quickly answer.
I add another server in nginx config file,and edit my hosts file.
It works.
