### ISSUE TITLE
Does ClickHouseDataSource have reusing ability? Or how can i manage connections?

### ISSUE THREAD

**Issue by ondevelop** [yandex/clickhouse-jdbc#231]
ClickHouseDataSource.getConnection() reports "r.yandex.clickhouse.ClickHouseDriver - Creating connection" on every calling.
Like a setMaxActive, setTestOnBorrow etc., as in the standard datasource
Thanks

**Comment by serebrserg** [comment]
Reuse of connections is not implemented. In current implementation every connection has an entire httpclient behind it, which manages its own pool of http connections. There are a couple of settings for that defined at https://github.com/yandex/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/settings/ClickHouseConnectionSettings.java
Because of that the correct way to use connections is to create one per target url with desired httpclient settings and stick with this one ClickhouseConnection.

**Comment by ondevelop** [comment]
ok, thanks for answer!
