### ISSUE TITLE
BigInteger value throw exception

### ISSUE THREAD

**Issue by rasmus93** [yandex/clickhouse-jdbc#56]
If we set BitInteger value in prepared statement it throw exception like this:
```java
 PreparedStatement st = null;
        try {
            st = new ClickHouseDataSource(
                    connections.get( 0 ),
                    properties
            ).getConnection().prepareStatement(
                    "INSERT INTO form_test(response_id,submit_date) VALUES (123, ?)" );
            st.setObject( 1, new BigInteger( "123" ) );
```
ClickHouse exception, code: 53, host: Code: 53, e.displayText() = DB::Exception: Type mismatch in IN or VALUES section: Int64 expected, String got: (at row 1), e.what() = DB::Exception

And question Int64 it is BigInteger value or Long?
Thanks!

**Comment by serebrserg** [comment]
Hi,
Do you use the latest version of the driver?
BigInteger support was fixed in 0.1.14 with unsigned types support.
I have a similar test as yours for this, and it works. Please check this out:
https://github.com/yandex/clickhouse-jdbc/blob/master/src/test/java/ru/yandex/clickhouse/integration/ClickHousePreparedStatementTest.java#L67
Does this solve the problem?

Regarding Int64 - on insert it doesn't actually matter as I know.
On select if you do getObject(), Int64 turns to Long, UInt64 turns to BigInteger.

**Comment by rasmus93** [comment]
Yes, updating to version 0.1.14 helps. Thanks!

And as I see in Int64 maximum value to store is equals to something like Long.MAX_VALUE.
Because if I insert value like "1000000000000000000000000000000000000000000000000" it transforms to value like this "9169610316303040512". Am I right?

**Comment by serebrserg** [comment]
Yes, Int64 is actually the same as Long, i.e. signed 64-bits integer, so you can store values from Long.MIN_VALUE to Long.MAX_VALUE in Int64 field. If you insert a value that is not in these limits, the value overflows until it fits.

**Comment by rasmus93** [comment]
Thanks!
