### ISSUE TITLE
executeBatch implementation

### ISSUE THREAD

**Issue by Badya** [yandex/clickhouse-jdbc#59]
@serebrserg @AndreevDm 

Currently i am working on integration between [metabase](https://github.com/metabase/metabase) and [ClickHouse](https://github.com/yandex/clickhouse).

It seems that clickhouse-jdbc driver doesn't provide support for formats like:
`INSERT INTO test.batch_insert (s, i) VALUES (?, ?), (?, ?)`
and
`INSERT INTO test.batch_insert (s, i) VALUES (?, 101), (?, 102)`

Looks like it is supported by ClickHouse (i've wrote some tests to theese formats and fixed 'em), so can it be supported in JDBC?

**Comment by serebrserg** [comment]
Hi.
As far as I understand the problem, it works:
```java
PreparedStatement statement = connection.prepareStatement("INSERT INTO test.batch_insert (s, i) VALUES (?, ?), (?, ?)");
statement.setString(1, "string1");
statement.setInt(2, 21);
statement.setString(3, "string2");
statement.setInt(4, 22);
statement.execute();
```

The second example:
```java
PreparedStatement statement = connection.prepareStatement("INSERT INTO test.batch_insert (s, i) VALUES (?, 22), (?, 23)");
statement.setString(1, "string1");
statement.setString(2, "string2");
statement.execute();
```

If I misunderstood the question, please attach your examples.

**Comment by Badya** [comment]
`PreparedStatement statement = connection.prepareStatement("INSERT INTO test.batch_insert (s, i) VALUES (?, ?), (?, ?)");
statement.setString(1, "str101");
statement.setInt(2, 101);
statement.setString(3, "str102");
statement.setInt(4, 102);
statement.addBatch();
statement.executeBatch();`

That's how JDBC API wraps PreparedStatement execution. (in my case i call it from closure.java.jdbc as jdbc/execute!)
And in this case we got: 
`DB::Exception: Cannot parse input: expected \n before: \t`
Which caused by method:
`ru.yandex.clickhouse.ClickHousePreparedStatementImpl#executeBatch`

I suppose because it throws away all "VALUES (?, ?) .." part of query instead of some standart PreparedStatement to SQLString convertion with parameters binding.

**Comment by lloonngg** [comment]
Hi, any update to this issue?  Would love to resolve this so that @Badya could hopefully complete a connector from Metabase to Clickhouse.  We are using Metabase internally for GreenPlum, and it is a fantastic interface for sql queries and visualization.  Being able to incorporate Clickhouse into Metabase would allow us to work on much larger datasets.

**Comment by Slach** [comment]
yep guys, i will happy see this feature will implemented

**Comment by serebrserg** [comment]
Hi. There hadn't been updates.
Let me describe my point:
- I agree that implementation differs from standard
- I agree that it would be good to allow different ways to express insert statements
- I think that current "bulk" insert must be encouraged to use and other types including ones in the issue must not, because they are not as effective for ClickHouse.

ClickHouse works effectively with big inserts up to 1M rows and the data for such "bulk" inserts may be compressed for network transfer.

The way I see to make best of both is to turn these complex inserts into simple "bulk" ones with some tricky parsing, which I wouldn't like to do, or leave current implementation for simple inserts, and "degrade" to copying values groups into query(making a long query with a lot of values groups) for complex ones, which will be less efficient, but easier to implement.
I prefer second option, with clear documentation that it is not efficient and is not recommended.
Does this sound reasonable for you and do you think it solves the problem?
If answer is positive I'll do this.
Anyway, contributions are welcome.

**Comment by Slach** [comment]
Yes, second option with clear documentation will look good
For us this implementation need only for passing internal compatibility tests Metabase and JDBC

**Comment by Badya** [comment]
@serebrserg, The JDBC API definition is kinda hard to overcome, when you use 3rd party lib implementing standart interface, you expect it to work as declared by interface. And simple idea of executeBatch not only DML inserts, but also some DDL statements executed one after another. 

I totally understand your point about effectiveness, but as i see it - we need a standart executeBatch implementation, with javadoc pointing to another method for bulk inserting into a clickhouse, containig information about performance optimizations.

**Comment by serebrserg** [comment]
In fact we could implement standard interface, making batches really batches of commands and optimize the case if there is one insert query with many params.
The problem is that as I see now ClickHouse doesn't support multiple statements, at least in http interface. 
@alexey-milovidov Alexey, is there a way to execute several statements in one request?

**Comment by akakimeladze** [comment]
Any updates on this topic? Metabase support will be huge step forward.
I see that Re:Dash is already supporting ClickHouse.

**Comment by serebrserg** [comment]
There wis no updates.
I invite anyone to submit a PR with what is discussed above, that:
- fixes the problem
- doesn't break current approach to batch inserts for simple cases that work now, with single (?, ?) and multiple data rows.

**Comment by enqueue** [comment]
I will give it a try

**Comment by serebrserg** [comment]
As I see all the cases are covered in https://github.com/yandex/clickhouse-jdbc/pull/246
If there are still problems, please reopen or file a new issue/PR with specific cases description.
Thanks for enqueue for great effort.
